### ISSUE TITLE
What's the differences in such projects

### ISSUE THREAD

**Issue by ChinaLym** [spring-io/asciidoctor-extensions#13]
Projects
-----

- [spring-io/spring-asciidoctor-extensions](https://github.com/spring-io/spring-asciidoctor-extensions)
- [spring-io/spring-asciidoctor-backends](https://github.com/spring-io/spring-asciidoctor-backends)
- [spring-io/asciidoctor-extensions](https://github.com/spring-io/asciidoctor-extensions)

-----
My View
-----
Hisotry

[spring-asciidoctor-extensions](https://github.com/spring-io/spring-asciidoctor-extensions) is the first asciidoc extension project, but it was deprecated now. So it better that pay more attention into other projects.

> `spring-asciidoctor-extensions` provide basic abilities: `double code block`、`Code Block` and more...

-----
Now-Maven（last version 2023.8）

`Spring Boot` lead the trend of `.yaml`/`.properties`, an another option ranther than  `xml`, and it support `kotlin`、`gradle`...

Based on the above background, [spring-asciidoctor-backends](https://github.com/spring-io/spring-asciidoctor-backends) replace it, a more powerful extansion in asciidoc.

> `asciidoctor-backends` provids features: `Spring looks and file`(eg. spring logo / spring color in css...)、Dark Mode、Code Chomping、Code Importing and more...

-----

Now-Node.JS

With the development of the static doc / Node.js, there were more factors appeard, such as `static search` (eg. `algolia` `pagefind`...), afterall, is's easier to modify `css` in a Node.js project.

[spring-io/asciidoctor-extensions](https://github.com/spring-io/asciidoctor-extensions) apperad, and it looks like a "official version" for release 1.0.xxx ?

---

And Spring Boot 3.x Doc is more buttiful than 2.x, it seams that the code is not here? Where can I obtain the way to generate a doc in Spring Boot 3.x looks and feel?

Thanks for your kind reply!

**Comment by philwebb** [comment]
Spring Boot 3.3 and beyond will be using Antora to generate documentation. Since Antora is Javascript based the existing https://github.com/spring-io/spring-asciidoctor-extensions project needed to be rewritten away from Java. The result of that is https://github.com/spring-io/asciidoctor-extensions.

The UI assets for the new site are at https://github.com/spring-io/antora-ui-spring.

**Comment by ChinaLym** [comment]
Thank you very much! ♥
