### ISSUE TITLE
Javadoc macro should offer a way to not print monospace text

### ISSUE THREAD

**Issue by philwebb** [spring-io/asciidoctor-extensions#17]

**Comment by rwinch** [comment]
I have it mostly sorted out here https://github.com/rwinch/asciidoctor-extensions/tree/subs-normal

You can try it with this sample https://github.com/rwinch/antora-sample/tree/attachments You will need to update the hardcoded paths to the extensions to your local file system

**Comment by philwebb** [comment]
More WIP at https://github.com/philwebb/asciidoctor-extensions/tree/gh-17

**Comment by philwebb** [comment]
Combined work submitted as PR #19
