### ISSUE TITLE
Allow `sync-group-id` to be configurable for `include-code` macro

### ISSUE THREAD

**Issue by sbrannen** [spring-io/asciidoctor-extensions#21]
For tab groups where we sometimes have Java/Kotlin and other times have Java/Kotlin/XML, I'd like to be able to manually sync those tab groups. For example, on [this page](https://docs.spring.io/spring-framework/reference/6.2-SNAPSHOT/integration/jmx/exporting.html).

The [documentation](https://github.com/asciidoctor/asciidoctor-tabs?tab=readme-ov-file#tabs-sync) for `asciidoctor-tabs` states that one can set the `sync-group-id`.

However, it is currently not possible to specify a custom `sync-group-id` when using the `include-code` macro, since the `[tabs]` output is hard-coded here:

https://github.com/spring-io/asciidoctor-extensions/blob/8157a35004eb7419dd5b23f6b2826d511b71be83/lib/include-code-extension.js#L68

It would be nice if we could configure the `sync-group-id` as follows. I picked `snippet` as an example, to align with the `tag` used, but it should be user-definable.

`include-code::./JmxTestBean[tag=snippet,indent=0,sync-group-id=snippet]`

That should generate `[tabs,sync-group-id=snippet]` instead of `[tabs]`.

**Comment by rwinch** [comment]
I've got a good start on the code for this, but am having trouble getting the tests to work properly. See https://github.com/rwinch/asciidoctor-extensions/commit/64736bfda517790dce8eea88c79c003513c43fde

**Comment by rwinch** [comment]
@sbrannen This is now merged into main and released in [1.0.0-alpha.14](https://github.com/spring-io/asciidoctor-extensions/milestone/6)

**Comment by sbrannen** [comment]
Awesome.

Thanks, @rwinch! 👍
